<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._CyDsEK' shared service.

return $this->privates['.service_locator._CyDsEK'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailer' => function (): \App\Services\Mailer {
    return ($this->privates['App\Services\Mailer'] ?? $this->load('getMailerService.php'));
}));
