<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCi3dogn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCi3dogn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCi3dogn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCi3dogn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCi3dogn\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ci3dogn',
    'container.build_id' => '563f5c98',
    'container.build_time' => 1537612316,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCi3dogn');
